// examples/attributify-prefix/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'

const foo = ref(false)
</script>

<template>
  <div
    w:text="xl lime-400"
    w:md="italic"
  >
    XL LIME
  </div>
  <div
    w:p="x-2 y-1"
    w:border="2"
    w:rounded="md"
    w:font="mono bold"
    w:hover:bg="gray-400 opacity-10"
    :w:bg="foo ? 'gray-200' : 'orange-400'"
    class="grid"
    @click="foo = !foo"
  >
    BOLD MONO
  </div>
  <div class="*app-border">
    app-border
  </div>
</template>

// examples/react/src/App.tsx
import React, { useState } from 'react'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="text-center">
      <header className="m-4">
        <p>Hello Vite + React!</p>
        <p>
          <button
            className="border border-gray-400 rounded px-4 py-2 mt-4 hover:(bg-teal-400 border-teal-400)"
            onClick={() => setCount(count => count + 1)}>
            count is: {count}
          </button>
        </p>
      </header>
    </div>
  )
}

export default App
