// examples/react/src/App.tsx
import React, { useState } from 'react'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="text-center">
      <header className="m-4">
        <p>Hello Vite + React!</p>
        <p>
          <button
            className="border border-gray-400 rounded px-4 py-2 mt-4 hover:(bg-teal-400 border-teal-400)"
            onClick={() => setCount(count => count + 1)}>
            count is: {count}
          </button>
        </p>
      </header>
    </div>
  )
}

export default App

// examples/windicss-v3/src/App.vue
<template>
  <div
    text="xl lime-400"
    md="italic"
  >
    XL LIME
  </div>
  <div
    p="x-2 y-1"
    border="2"
    rounded="md"
    font="mono bold"
    hover:bg="gray-400 opacity-10"
    class="grid"
  >
    BOLD MONO
  </div>
  <div class="*app-border">
    app-border
  </div>
</template>
