// examples/react/src/App.tsx
import React, { useState } from 'react'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="text-center">
      <header className="m-4">
        <p>Hello Vite + React!</p>
        <p>
          <button
            className="border border-gray-400 rounded px-4 py-2 mt-4 hover:(bg-teal-400 border-teal-400)"
            onClick={() => setCount(count => count + 1)}>
            count is: {count}
          </button>
        </p>
      </header>
    </div>
  )
}

export default App

// example/src/App.vue
<template>
  <div
    class="px-5 p-1 text-white hover:(text-green-100 rounded-full)"
    :class="{ 'bg-teal-100': true, 'hover:w-1/3': true }"
  >
    Hello World
  </div>
  <h2 class="button">
    Button
  </h2>
  <div class="foo">
    foo
  </div>
  <router-link />
</template>

<style lang="postcss">
.foo {
  @apply rounded-full bg-pink-400 text-white p-4 w-1/4;
}
</style>
